### PR TITLE
Bump alpine version. Fixes #8

### LINKED ISSUE #8: Bump alpine version
Hi @Meroje 

Could you bump the alpine version. It's getting quite old.

Thanks :)

### PR DESCRIPTION
**Pull request by jody-frankowski**

### CODE REVIEW

**Comment by jody-frankowski** [comment]
Wow, I am very sad that you didn't provide any build instructions. I was not expecting I'd have to rely on the closed Dockercloud platform to test my changes...

**Comment by Meroje** [comment]
well that's handy, my image will be ready in time for 3.7's release, thanks !

**Comment by jody-frankowski** [comment]
Awesome!

**Comment by jody-frankowski** [comment]
Thanks @Meroje !

**Comment by Meroje** [comment]
Will be published in the next tag, thanks again and sorry being so late to merge

**Pull request merged**
